[package]
name = "render_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
cgmath = "0.18.0"
env_logger = "0.11.8"
image = "0.25.0"
pollster = "0.4.0"
tobj = "4.0.2"
wgpu = "27.0.1"
winit = "0.30.12"
